name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: tim9h
        server-password-env-var: READ_PACKAGES_PAT
        mvn-repositories: |
          github:https://maven.pkg.github.com/tim9h/*:true

    # Runs on Pull Requests only
    - name: Build with Maven
      if: github.event_name == 'pull_request'
      run: mvn -B package --file pom.xml
      env:
        READ_PACKAGES_PAT: ${{ secrets.READ_PACKAGES_PAT }}

    # Runs on Push to master only
    - name: Publish to GitHub Packages
      if: github.event_name == 'push'
      run: mvn -B deploy --file pom.xml -DskipTests=false
      env:
        READ_PACKAGES_PAT: ${{ secrets.READ_PACKAGES_PAT }}